# Generated by Django 2.1.2 on 2018-10-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('especificaiones', models.CharField(max_length=200)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCuenta', models.CharField(max_length=200)),
            ],
        ),
    ]
