# Generated by Django 2.1.2 on 2018-10-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='idTipoCuenta',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='contabilidad.TipoCuenta'),
        ),
    ]
