# Generated by Django 2.1.2 on 2018-10-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cuenta_idtipocuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='especificaiones',
            new_name='descripcion',
        ),
    ]
