# Generated by Django 2.1.2 on 2018-11-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20181016_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha', models.DateField()),
                ('fechaRegistro', models.DateField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('detalle', models.ManyToManyField(to='contabilidad.DetalleTransaccion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Periodo')),
            ],
        ),
    ]
