# Generated by Django 2.1.2 on 2018-11-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_detalletransaccion_periodo_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='debe',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='detalle',
            field=models.ManyToManyField(blank=True, to='contabilidad.DetalleTransaccion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='haber',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Periodo'),
        ),
    ]
