# Generated by Django 2.1.2 on 2018-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20181105_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='debe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='haber',
            field=models.FloatField(default=0),
        ),
    ]
