# Generated by Django 2.1.2 on 2018-11-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_auto_20181105_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='debe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='haber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Periodo'),
        ),
    ]
